# DockerImageサイズを小さくするためslimイメージを使用してマルチステージビルドを行う
# Build
FROM node:22-bookworm-slim AS build

WORKDIR /app
COPY . .
RUN npm install -g bun
RUN bun install
RUN bun run build
RUN rm -rf node_modules
RUN bun install --production

# Production
FROM node:22-bookworm-slim AS production

WORKDIR /app
COPY --from=build /app/.next ./.next
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/next.config.ts ./next.config.ts
COPY --from=build /app/node_modules ./node_modules

EXPOSE 3000
CMD ["npm", "start"]
