name: Build and deploy Docker app to Azure

on:
  push:
    branches:
      - main

# env:
#   TARGET_ENVIRONMENT: dev # Azure上で作成したフェデレーション資格情報の環境と一致させる

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    env:
      DOCKER_IMAGE_NAME: ${{ vars.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ vars.AZURE_WEBAPP_NAME }}:latest # ACRの容量を節約するため常にlatestを更新
    permissions:
      id-token: write # OIDC 接続を実行するために必要
    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v3
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - run: az webapp list -o table
      # - name: Login to container registry
      #   run: az acr login -n ${{ vars.AZURE_CONTAINER_REGISTRY_NAME }}
      # - name: Build and push container image to registry
      #   run: |
      #     docker build -t ${{ env.DOCKER_IMAGE_NAME }} -f Dockerfile.dev .
      #     docker push ${{ env.DOCKER_IMAGE_NAME }}
      # - run: echo "${{ vars.AZURE_WEBAPP_NAME }}"
      # - name: 'Deploy to Azure Web App'
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: ${{ vars.AZURE_WEBAPP_NAME }}
      #     images: ${{ env.DOCKER_IMAGE_NAME }}
      # - name: Restart Azure Web App
      #   run: echo "Deploy to Azure Web App"
