name: Build and deploy Docker app to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev # Azure上で作成したフェデレーション資格情報の環境と一致させる
    permissions:
      id-token: write # OIDC 接続を実行するために必要
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Test access to Azure
        run: |
          az account show --query name

      # - name: Login to container registry
      #   run: az acr login -n xxxx

      # - name: Build and push container image to registry
      #   run: |
      #     docker build -t xxxx.azurecr.io/wincontainer-test:${{ github.sha }} -f ./app/Dockerfile ./app/
      #     docker push xxxx.azurecr.io/wincontainer-test:${{ github.sha }}

      # - name: 'Azure Web App for Containerへのデプロイ'
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: ${{ env.AZURE_WEBAPP_NAME }}
      #     images: ${{ env.CONTAINER_REGISTRY }}/nodejsapp:${{ github.sha }}
